// State-specific county mappings for dynamic dropdowns
export const stateCounties = {
  'AL': [
    { value: 'Autauga', label: 'Autauga County' },
    { value: 'Baldwin', label: 'Baldwin County' },
    { value: 'Barbour', label: 'Barbour County' },
    { value: 'Bibb', label: 'Bibb County' },
    { value: 'Blount', label: 'Blount County' },
    { value: 'Bullock', label: 'Bullock County' },
    { value: 'Butler', label: 'Butler County' },
    { value: 'Calhoun', label: 'Calhoun County' },
    { value: 'Chambers', label: 'Chambers County' },
    { value: 'Cherokee', label: 'Cherokee County' },
    { value: 'Chilton', label: 'Chilton County' },
    { value: 'Choctaw', label: 'Choctaw County' },
    { value: 'Clarke', label: 'Clarke County' },
    { value: 'Clay', label: 'Clay County' },
    { value: 'Cleburne', label: 'Cleburne County' },
    { value: 'Coffee', label: 'Coffee County' },
    { value: 'Colbert', label: 'Colbert County' },
    { value: 'Conecuh', label: 'Conecuh County' },
    { value: 'Coosa', label: 'Coosa County' },
    { value: 'Covington', label: 'Covington County' },
    { value: 'Crenshaw', label: 'Crenshaw County' },
    { value: 'Cullman', label: 'Cullman County' },
    { value: 'Dale', label: 'Dale County' },
    { value: 'Dallas', label: 'Dallas County' },
    { value: 'DeKalb', label: 'DeKalb County' },
    { value: 'Elmore', label: 'Elmore County' },
    { value: 'Escambia', label: 'Escambia County' },
    { value: 'Etowah', label: 'Etowah County' },
    { value: 'Fayette', label: 'Fayette County' },
    { value: 'Franklin', label: 'Franklin County' },
    { value: 'Geneva', label: 'Geneva County' },
    { value: 'Greene', label: 'Greene County' },
    { value: 'Hale', label: 'Hale County' },
    { value: 'Henry', label: 'Henry County' },
    { value: 'Houston', label: 'Houston County' },
    { value: 'Jackson', label: 'Jackson County' },
    { value: 'Jefferson', label: 'Jefferson County' },
    { value: 'Lamar', label: 'Lamar County' },
    { value: 'Lauderdale', label: 'Lauderdale County' },
    { value: 'Lawrence', label: 'Lawrence County' },
    { value: 'Lee', label: 'Lee County' },
    { value: 'Limestone', label: 'Limestone County' },
    { value: 'Lowndes', label: 'Lowndes County' },
    { value: 'Macon', label: 'Macon County' },
    { value: 'Madison', label: 'Madison County' },
    { value: 'Marengo', label: 'Marengo County' },
    { value: 'Marion', label: 'Marion County' },
    { value: 'Marshall', label: 'Marshall County' },
    { value: 'Mobile', label: 'Mobile County' },
    { value: 'Monroe', label: 'Monroe County' },
    { value: 'Montgomery', label: 'Montgomery County' },
    { value: 'Morgan', label: 'Morgan County' },
    { value: 'Perry', label: 'Perry County' },
    { value: 'Pickens', label: 'Pickens County' },
    { value: 'Pike', label: 'Pike County' },
    { value: 'Randolph', label: 'Randolph County' },
    { value: 'Russell', label: 'Russell County' },
    { value: 'St. Clair', label: 'St. Clair County' },
    { value: 'Shelby', label: 'Shelby County' },
    { value: 'Sumter', label: 'Sumter County' },
    { value: 'Talladega', label: 'Talladega County' },
    { value: 'Tallapoosa', label: 'Tallapoosa County' },
    { value: 'Tuscaloosa', label: 'Tuscaloosa County' },
    { value: 'Walker', label: 'Walker County' },
    { value: 'Washington', label: 'Washington County' },
    { value: 'Wilcox', label: 'Wilcox County' },
    { value: 'Winston', label: 'Winston County' }
  ],
  'FL': [
    { value: 'Alachua', label: 'Alachua County' },
    { value: 'Baker', label: 'Baker County' },
    { value: 'Bay', label: 'Bay County' },
    { value: 'Bradford', label: 'Bradford County' },
    { value: 'Brevard', label: 'Brevard County' },
    { value: 'Broward', label: 'Broward County' },
    { value: 'Calhoun', label: 'Calhoun County' },
    { value: 'Charlotte', label: 'Charlotte County' },
    { value: 'Citrus', label: 'Citrus County' },
    { value: 'Clay', label: 'Clay County' },
    { value: 'Collier', label: 'Collier County' },
    { value: 'Columbia', label: 'Columbia County' },
    { value: 'DeSoto', label: 'DeSoto County' },
    { value: 'Dixie', label: 'Dixie County' },
    { value: 'Duval', label: 'Duval County' },
    { value: 'Escambia', label: 'Escambia County' },
    { value: 'Flagler', label: 'Flagler County' },
    { value: 'Franklin', label: 'Franklin County' },
    { value: 'Gadsden', label: 'Gadsden County' },
    { value: 'Gilchrist', label: 'Gilchrist County' },
    { value: 'Glades', label: 'Glades County' },
    { value: 'Gulf', label: 'Gulf County' },
    { value: 'Hamilton', label: 'Hamilton County' },
    { value: 'Hardee', label: 'Hardee County' },
    { value: 'Hendry', label: 'Hendry County' },
    { value: 'Hernando', label: 'Hernando County' },
    { value: 'Highlands', label: 'Highlands County' },
    { value: 'Hillsborough', label: 'Hillsborough County' },
    { value: 'Holmes', label: 'Holmes County' },
    { value: 'Indian River', label: 'Indian River County' },
    { value: 'Jackson', label: 'Jackson County' },
    { value: 'Jefferson', label: 'Jefferson County' },
    { value: 'Lafayette', label: 'Lafayette County' },
    { value: 'Lake', label: 'Lake County' },
    { value: 'Lee', label: 'Lee County' },
    { value: 'Leon', label: 'Leon County' },
    { value: 'Levy', label: 'Levy County' },
    { value: 'Liberty', label: 'Liberty County' },
    { value: 'Madison', label: 'Madison County' },
    { value: 'Manatee', label: 'Manatee County' },
    { value: 'Marion', label: 'Marion County' },
    { value: 'Martin', label: 'Martin County' },
    { value: 'Miami-Dade', label: 'Miami-Dade County' },
    { value: 'Monroe', label: 'Monroe County' },
    { value: 'Nassau', label: 'Nassau County' },
    { value: 'Okaloosa', label: 'Okaloosa County' },
    { value: 'Okeechobee', label: 'Okeechobee County' },
    { value: 'Orange', label: 'Orange County' },
    { value: 'Osceola', label: 'Osceola County' },
    { value: 'Palm Beach', label: 'Palm Beach County' },
    { value: 'Pasco', label: 'Pasco County' },
    { value: 'Pinellas', label: 'Pinellas County' },
    { value: 'Polk', label: 'Polk County' },
    { value: 'Putnam', label: 'Putnam County' },
    { value: 'Santa Rosa', label: 'Santa Rosa County' },
    { value: 'Sarasota', label: 'Sarasota County' },
    { value: 'Seminole', label: 'Seminole County' },
    { value: 'St. Johns', label: 'St. Johns County' },
    { value: 'St. Lucie', label: 'St. Lucie County' },
    { value: 'Sumter', label: 'Sumter County' },
    { value: 'Suwannee', label: 'Suwannee County' },
    { value: 'Taylor', label: 'Taylor County' },
    { value: 'Union', label: 'Union County' },
    { value: 'Volusia', label: 'Volusia County' },
    { value: 'Wakulla', label: 'Wakulla County' },
    { value: 'Walton', label: 'Walton County' },
    { value: 'Washington', label: 'Washington County' }
  ],
  'NY': [
    { value: 'Albany', label: 'Albany County' },
    { value: 'Allegany', label: 'Allegany County' },
    { value: 'Bronx', label: 'Bronx County' },
    { value: 'Broome', label: 'Broome County' },
    { value: 'Cattaraugus', label: 'Cattaraugus County' },
    { value: 'Cayuga', label: 'Cayuga County' },
    { value: 'Chautauqua', label: 'Chautauqua County' },
    { value: 'Chemung', label: 'Chemung County' },
    { value: 'Chenango', label: 'Chenango County' },
    { value: 'Clinton', label: 'Clinton County' },
    { value: 'Columbia', label: 'Columbia County' },
    { value: 'Cortland', label: 'Cortland County' },
    { value: 'Delaware', label: 'Delaware County' },
    { value: 'Dutchess', label: 'Dutchess County' },
    { value: 'Erie', label: 'Erie County' },
    { value: 'Essex', label: 'Essex County' },
    { value: 'Franklin', label: 'Franklin County' },
    { value: 'Fulton', label: 'Fulton County' },
    { value: 'Genesee', label: 'Genesee County' },
    { value: 'Greene', label: 'Greene County' },
    { value: 'Hamilton', label: 'Hamilton County' },
    { value: 'Herkimer', label: 'Herkimer County' },
    { value: 'Jefferson', label: 'Jefferson County' },
    { value: 'Kings', label: 'Kings County' },
    { value: 'Lewis', label: 'Lewis County' },
    { value: 'Livingston', label: 'Livingston County' },
    { value: 'Madison', label: 'Madison County' },
    { value: 'Monroe', label: 'Monroe County' },
    { value: 'Montgomery', label: 'Montgomery County' },
    { value: 'Nassau', label: 'Nassau County' },
    { value: 'New York', label: 'New York County' },
    { value: 'Niagara', label: 'Niagara County' },
    { value: 'Oneida', label: 'Oneida County' },
    { value: 'Onondaga', label: 'Onondaga County' },
    { value: 'Ontario', label: 'Ontario County' },
    { value: 'Orange', label: 'Orange County' },
    { value: 'Orleans', label: 'Orleans County' },
    { value: 'Oswego', label: 'Oswego County' },
    { value: 'Otsego', label: 'Otsego County' },
    { value: 'Putnam', label: 'Putnam County' },
    { value: 'Queens', label: 'Queens County' },
    { value: 'Rensselaer', label: 'Rensselaer County' },
    { value: 'Richmond', label: 'Richmond County' },
    { value: 'Rockland', label: 'Rockland County' },
    { value: 'St. Lawrence', label: 'St. Lawrence County' },
    { value: 'Saratoga', label: 'Saratoga County' },
    { value: 'Schenectady', label: 'Schenectady County' },
    { value: 'Schoharie', label: 'Schoharie County' },
    { value: 'Schuyler', label: 'Schuyler County' },
    { value: 'Seneca', label: 'Seneca County' },
    { value: 'Steuben', label: 'Steuben County' },
    { value: 'Suffolk', label: 'Suffolk County' },
    { value: 'Sullivan', label: 'Sullivan County' },
    { value: 'Tioga', label: 'Tioga County' },
    { value: 'Tompkins', label: 'Tompkins County' },
    { value: 'Ulster', label: 'Ulster County' },
    { value: 'Warren', label: 'Warren County' },
    { value: 'Washington', label: 'Washington County' },
    { value: 'Wayne', label: 'Wayne County' },
    { value: 'Westchester', label: 'Westchester County' },
    { value: 'Wyoming', label: 'Wyoming County' },
    { value: 'Yates', label: 'Yates County' }
  ],
  'CA': [
    { value: 'Alameda', label: 'Alameda County' },
    { value: 'Alpine', label: 'Alpine County' },
    { value: 'Amador', label: 'Amador County' },
    { value: 'Butte', label: 'Butte County' },
    { value: 'Calaveras', label: 'Calaveras County' },
    { value: 'Colusa', label: 'Colusa County' },
    { value: 'Contra Costa', label: 'Contra Costa County' },
    { value: 'Del Norte', label: 'Del Norte County' },
    { value: 'El Dorado', label: 'El Dorado County' },
    { value: 'Fresno', label: 'Fresno County' },
    { value: 'Glenn', label: 'Glenn County' },
    { value: 'Humboldt', label: 'Humboldt County' },
    { value: 'Imperial', label: 'Imperial County' },
    { value: 'Inyo', label: 'Inyo County' },
    { value: 'Kern', label: 'Kern County' },
    { value: 'Kings', label: 'Kings County' },
    { value: 'Lake', label: 'Lake County' },
    { value: 'Lassen', label: 'Lassen County' },
    { value: 'Los Angeles', label: 'Los Angeles County' },
    { value: 'Madera', label: 'Madera County' },
    { value: 'Marin', label: 'Marin County' },
    { value: 'Mariposa', label: 'Mariposa County' },
    { value: 'Mendocino', label: 'Mendocino County' },
    { value: 'Merced', label: 'Merced County' },
    { value: 'Modoc', label: 'Modoc County' },
    { value: 'Mono', label: 'Mono County' },
    { value: 'Monterey', label: 'Monterey County' },
    { value: 'Napa', label: 'Napa County' },
    { value: 'Nevada', label: 'Nevada County' },
    { value: 'Orange', label: 'Orange County' },
    { value: 'Placer', label: 'Placer County' },
    { value: 'Plumas', label: 'Plumas County' },
    { value: 'Riverside', label: 'Riverside County' },
    { value: 'Sacramento', label: 'Sacramento County' },
    { value: 'San Benito', label: 'San Benito County' },
    { value: 'San Bernardino', label: 'San Bernardino County' },
    { value: 'San Diego', label: 'San Diego County' },
    { value: 'San Francisco', label: 'San Francisco County' },
    { value: 'San Joaquin', label: 'San Joaquin County' },
    { value: 'San Luis Obispo', label: 'San Luis Obispo County' },
    { value: 'San Mateo', label: 'San Mateo County' },
    { value: 'Santa Barbara', label: 'Santa Barbara County' },
    { value: 'Santa Clara', label: 'Santa Clara County' },
    { value: 'Santa Cruz', label: 'Santa Cruz County' },
    { value: 'Shasta', label: 'Shasta County' },
    { value: 'Sierra', label: 'Sierra County' },
    { value: 'Siskiyou', label: 'Siskiyou County' },
    { value: 'Solano', label: 'Solano County' },
    { value: 'Sonoma', label: 'Sonoma County' },
    { value: 'Stanislaus', label: 'Stanislaus County' },
    { value: 'Sutter', label: 'Sutter County' },
    { value: 'Tehama', label: 'Tehama County' },
    { value: 'Trinity', label: 'Trinity County' },
    { value: 'Tulare', label: 'Tulare County' },
    { value: 'Tuolumne', label: 'Tuolumne County' },
    { value: 'Ventura', label: 'Ventura County' },
    { value: 'Yolo', label: 'Yolo County' },
    { value: 'Yuba', label: 'Yuba County' }
  ],
  'TX': [
    { value: 'Anderson', label: 'Anderson County' },
    { value: 'Andrews', label: 'Andrews County' },
    { value: 'Angelina', label: 'Angelina County' },
    { value: 'Aransas', label: 'Aransas County' },
    { value: 'Archer', label: 'Archer County' },
    { value: 'Armstrong', label: 'Armstrong County' },
    { value: 'Atascosa', label: 'Atascosa County' },
    { value: 'Austin', label: 'Austin County' },
    { value: 'Bailey', label: 'Bailey County' },
    { value: 'Bandera', label: 'Bandera County' },
    { value: 'Bastrop', label: 'Bastrop County' },
    { value: 'Baylor', label: 'Baylor County' },
    { value: 'Bee', label: 'Bee County' },
    { value: 'Bell', label: 'Bell County' },
    { value: 'Bexar', label: 'Bexar County' },
    { value: 'Blanco', label: 'Blanco County' },
    { value: 'Borden', label: 'Borden County' },
    { value: 'Bosque', label: 'Bosque County' },
    { value: 'Bowie', label: 'Bowie County' },
    { value: 'Brazoria', label: 'Brazoria County' },
    { value: 'Brazos', label: 'Brazos County' },
    { value: 'Brewster', label: 'Brewster County' },
    { value: 'Briscoe', label: 'Briscoe County' },
    { value: 'Brooks', label: 'Brooks County' },
    { value: 'Brown', label: 'Brown County' },
    { value: 'Burleson', label: 'Burleson County' },
    { value: 'Burnet', label: 'Burnet County' },
    { value: 'Caldwell', label: 'Caldwell County' },
    { value: 'Calhoun', label: 'Calhoun County' },
    { value: 'Callahan', label: 'Callahan County' },
    { value: 'Cameron', label: 'Cameron County' },
    { value: 'Camp', label: 'Camp County' },
    { value: 'Carson', label: 'Carson County' },
    { value: 'Cass', label: 'Cass County' },
    { value: 'Castro', label: 'Castro County' },
    { value: 'Chambers', label: 'Chambers County' },
    { value: 'Cherokee', label: 'Cherokee County' },
    { value: 'Childress', label: 'Childress County' },
    { value: 'Clay', label: 'Clay County' },
    { value: 'Cochran', label: 'Cochran County' },
    { value: 'Coke', label: 'Coke County' },
    { value: 'Coleman', label: 'Coleman County' },
    { value: 'Collin', label: 'Collin County' },
    { value: 'Collingsworth', label: 'Collingsworth County' },
    { value: 'Colorado', label: 'Colorado County' },
    { value: 'Comal', label: 'Comal County' },
    { value: 'Comanche', label: 'Comanche County' },
    { value: 'Concho', label: 'Concho County' },
    { value: 'Cooke', label: 'Cooke County' },
    { value: 'Coryell', label: 'Coryell County' },
    { value: 'Cottle', label: 'Cottle County' },
    { value: 'Crane', label: 'Crane County' },
    { value: 'Crockett', label: 'Crockett County' },
    { value: 'Crosby', label: 'Crosby County' },
    { value: 'Culberson', label: 'Culberson County' },
    { value: 'Dallam', label: 'Dallam County' },
    { value: 'Dallas', label: 'Dallas County' },
    { value: 'Dawson', label: 'Dawson County' },
    { value: 'Deaf Smith', label: 'Deaf Smith County' },
    { value: 'Delta', label: 'Delta County' },
    { value: 'Denton', label: 'Denton County' },
    { value: 'DeWitt', label: 'DeWitt County' },
    { value: 'Dickens', label: 'Dickens County' },
    { value: 'Dimmit', label: 'Dimmit County' },
    { value: 'Donley', label: 'Donley County' },
    { value: 'Duval', label: 'Duval County' },
    { value: 'Eastland', label: 'Eastland County' },
    { value: 'Ector', label: 'Ector County' },
    { value: 'Edwards', label: 'Edwards County' },
    { value: 'Ellis', label: 'Ellis County' },
    { value: 'El Paso', label: 'El Paso County' },
    { value: 'Erath', label: 'Erath County' },
    { value: 'Falls', label: 'Falls County' },
    { value: 'Fannin', label: 'Fannin County' },
    { value: 'Fayette', label: 'Fayette County' },
    { value: 'Fisher', label: 'Fisher County' },
    { value: 'Floyd', label: 'Floyd County' },
    { value: 'Foard', label: 'Foard County' },
    { value: 'Fort Bend', label: 'Fort Bend County' },
    { value: 'Franklin', label: 'Franklin County' },
    { value: 'Freestone', label: 'Freestone County' },
    { value: 'Frio', label: 'Frio County' },
    { value: 'Gaines', label: 'Gaines County' },
    { value: 'Galveston', label: 'Galveston County' },
    { value: 'Garza', label: 'Garza County' },
    { value: 'Gillespie', label: 'Gillespie County' },
    { value: 'Glasscock', label: 'Glasscock County' },
    { value: 'Goliad', label: 'Goliad County' },
    { value: 'Gonzales', label: 'Gonzales County' },
    { value: 'Gray', label: 'Gray County' },
    { value: 'Grayson', label: 'Grayson County' },
    { value: 'Gregg', label: 'Gregg County' },
    { value: 'Grimes', label: 'Grimes County' },
    { value: 'Guadalupe', label: 'Guadalupe County' },
    { value: 'Hale', label: 'Hale County' },
    { value: 'Hall', label: 'Hall County' },
    { value: 'Hamilton', label: 'Hamilton County' },
    { value: 'Hansford', label: 'Hansford County' },
    { value: 'Hardeman', label: 'Hardeman County' },
    { value: 'Hardin', label: 'Hardin County' },
    { value: 'Harris', label: 'Harris County' },
    { value: 'Harrison', label: 'Harrison County' },
    { value: 'Hartley', label: 'Hartley County' },
    { value: 'Haskell', label: 'Haskell County' },
    { value: 'Hays', label: 'Hays County' },
    { value: 'Hemphill', label: 'Hemphill County' },
    { value: 'Henderson', label: 'Henderson County' },
    { value: 'Hidalgo', label: 'Hidalgo County' },
    { value: 'Hill', label: 'Hill County' },
    { value: 'Hockley', label: 'Hockley County' },
    { value: 'Hood', label: 'Hood County' },
    { value: 'Hopkins', label: 'Hopkins County' },
    { value: 'Houston', label: 'Houston County' },
    { value: 'Howard', label: 'Howard County' },
    { value: 'Hudspeth', label: 'Hudspeth County' },
    { value: 'Hunt', label: 'Hunt County' },
    { value: 'Hutchinson', label: 'Hutchinson County' },
    { value: 'Irion', label: 'Irion County' },
    { value: 'Jack', label: 'Jack County' },
    { value: 'Jackson', label: 'Jackson County' },
    { value: 'Jasper', label: 'Jasper County' },
    { value: 'Jeff Davis', label: 'Jeff Davis County' },
    { value: 'Jefferson', label: 'Jefferson County' },
    { value: 'Jim Hogg', label: 'Jim Hogg County' },
    { value: 'Jim Wells', label: 'Jim Wells County' },
    { value: 'Johnson', label: 'Johnson County' },
    { value: 'Jones', label: 'Jones County' },
    { value: 'Karnes', label: 'Karnes County' },
    { value: 'Kaufman', label: 'Kaufman County' },
    { value: 'Kendall', label: 'Kendall County' },
    { value: 'Kenedy', label: 'Kenedy County' },
    { value: 'Kent', label: 'Kent County' },
    { value: 'Kerr', label: 'Kerr County' },
    { value: 'Kimble', label: 'Kimble County' },
    { value: 'King', label: 'King County' },
    { value: 'Kinney', label: 'Kinney County' },
    { value: 'Kleberg', label: 'Kleberg County' },
    { value: 'Knox', label: 'Knox County' },
    { value: 'Lamar', label: 'Lamar County' },
    { value: 'Lamb', label: 'Lamb County' },
    { value: 'Lampasas', label: 'Lampasas County' },
    { value: 'La Salle', label: 'La Salle County' },
    { value: 'Lavaca', label: 'Lavaca County' },
    { value: 'Lee', label: 'Lee County' },
    { value: 'Leon', label: 'Leon County' },
    { value: 'Liberty', label: 'Liberty County' },
    { value: 'Limestone', label: 'Limestone County' },
    { value: 'Lipscomb', label: 'Lipscomb County' },
    { value: 'Live Oak', label: 'Live Oak County' },
    { value: 'Llano', label: 'Llano County' },
    { value: 'Loving', label: 'Loving County' },
    { value: 'Lubbock', label: 'Lubbock County' },
    { value: 'Lynn', label: 'Lynn County' },
    { value: 'McCulloch', label: 'McCulloch County' },
    { value: 'McLennan', label: 'McLennan County' },
    { value: 'McMullen', label: 'McMullen County' },
    { value: 'Madison', label: 'Madison County' },
    { value: 'Marion', label: 'Marion County' },
    { value: 'Martin', label: 'Martin County' },
    { value: 'Mason', label: 'Mason County' },
    { value: 'Matagorda', label: 'Matagorda County' },
    { value: 'Maverick', label: 'Maverick County' },
    { value: 'Medina', label: 'Medina County' },
    { value: 'Menard', label: 'Menard County' },
    { value: 'Midland', label: 'Midland County' },
    { value: 'Milam', label: 'Milam County' },
    { value: 'Mills', label: 'Mills County' },
    { value: 'Mitchell', label: 'Mitchell County' },
    { value: 'Montague', label: 'Montague County' },
    { value: 'Montgomery', label: 'Montgomery County' },
    { value: 'Moore', label: 'Moore County' },
    { value: 'Morris', label: 'Morris County' },
    { value: 'Motley', label: 'Motley County' },
    { value: 'Nacogdoches', label: 'Nacogdoches County' },
    { value: 'Navarro', label: 'Navarro County' },
    { value: 'Newton', label: 'Newton County' },
    { value: 'Nolan', label: 'Nolan County' },
    { value: 'Nueces', label: 'Nueces County' },
    { value: 'Ochiltree', label: 'Ochiltree County' },
    { value: 'Oldham', label: 'Oldham County' },
    { value: 'Orange', label: 'Orange County' },
    { value: 'Palo Pinto', label: 'Palo Pinto County' },
    { value: 'Panola', label: 'Panola County' },
    { value: 'Parker', label: 'Parker County' },
    { value: 'Parmer', label: 'Parmer County' },
    { value: 'Pecos', label: 'Pecos County' },
    { value: 'Polk', label: 'Polk County' },
    { value: 'Potter', label: 'Potter County' },
    { value: 'Presidio', label: 'Presidio County' },
    { value: 'Rains', label: 'Rains County' },
    { value: 'Randall', label: 'Randall County' },
    { value: 'Reagan', label: 'Reagan County' },
    { value: 'Real', label: 'Real County' },
    { value: 'Red River', label: 'Red River County' },
    { value: 'Reeves', label: 'Reeves County' },
    { value: 'Refugio', label: 'Refugio County' },
    { value: 'Roberts', label: 'Roberts County' },
    { value: 'Robertson', label: 'Robertson County' },
    { value: 'Rockwall', label: 'Rockwall County' },
    { value: 'Runnels', label: 'Runnels County' },
    { value: 'Rusk', label: 'Rusk County' },
    { value: 'Sabine', label: 'Sabine County' },
    { value: 'San Augustine', label: 'San Augustine County' },
    { value: 'San Jacinto', label: 'San Jacinto County' },
    { value: 'San Patricio', label: 'San Patricio County' },
    { value: 'San Saba', label: 'San Saba County' },
    { value: 'Schleicher', label: 'Schleicher County' },
    { value: 'Scurry', label: 'Scurry County' },
    { value: 'Shackelford', label: 'Shackelford County' },
    { value: 'Shelby', label: 'Shelby County' },
    { value: 'Sherman', label: 'Sherman County' },
    { value: 'Smith', label: 'Smith County' },
    { value: 'Somervell', label: 'Somervell County' },
    { value: 'Starr', label: 'Starr County' },
    { value: 'Stephens', label: 'Stephens County' },
    { value: 'Sterling', label: 'Sterling County' },
    { value: 'Stonewall', label: 'Stonewall County' },
    { value: 'Sutton', label: 'Sutton County' },
    { value: 'Swisher', label: 'Swisher County' },
    { value: 'Tarrant', label: 'Tarrant County' },
    { value: 'Taylor', label: 'Taylor County' },
    { value: 'Terrell', label: 'Terrell County' },
    { value: 'Terry', label: 'Terry County' },
    { value: 'Throckmorton', label: 'Throckmorton County' },
    { value: 'Titus', label: 'Titus County' },
    { value: 'Tom Green', label: 'Tom Green County' },
    { value: 'Travis', label: 'Travis County' },
    { value: 'Trinity', label: 'Trinity County' },
    { value: 'Tyler', label: 'Tyler County' },
    { value: 'Upshur', label: 'Upshur County' },
    { value: 'Upton', label: 'Upton County' },
    { value: 'Uvalde', label: 'Uvalde County' },
    { value: 'Val Verde', label: 'Val Verde County' },
    { value: 'Van Zandt', label: 'Van Zandt County' },
    { value: 'Victoria', label: 'Victoria County' },
    { value: 'Walker', label: 'Walker County' },
    { value: 'Waller', label: 'Waller County' },
    { value: 'Ward', label: 'Ward County' },
    { value: 'Washington', label: 'Washington County' },
    { value: 'Webb', label: 'Webb County' },
    { value: 'Wharton', label: 'Wharton County' },
    { value: 'Wheeler', label: 'Wheeler County' },
    { value: 'Wichita', label: 'Wichita County' },
    { value: 'Wilbarger', label: 'Wilbarger County' },
    { value: 'Willacy', label: 'Willacy County' },
    { value: 'Williamson', label: 'Williamson County' },
    { value: 'Wilson', label: 'Wilson County' },
    { value: 'Winkler', label: 'Winkler County' },
    { value: 'Wise', label: 'Wise County' },
    { value: 'Wood', label: 'Wood County' },
    { value: 'Yoakum', label: 'Yoakum County' },
    { value: 'Young', label: 'Young County' },
    { value: 'Zapata', label: 'Zapata County' },
    { value: 'Zavala', label: 'Zavala County' }
  ]
}

// Function to get counties for a specific state
export function getCountiesForState(stateCode) {
  return stateCounties[stateCode] || []
}

// Function to get all available states
export function getAvailableStates() {
  return Object.keys(stateCounties)
}
