[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "npm --prefix client install --production=false",
  "npm --prefix server install --production=false"
]

[phases.build]
cmds = [
  "npm --prefix client run build"
]

[start]
cmd = "cd server && npm start"

